# we only need to point to python for the tests to run
language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"

# conda setup
before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - bash ./miniconda.sh -b -p $HOME/miniconda2
  - export PATH="$HOME/miniconda2/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pandas lxml networkx python-levenshtein
  - source activate test-environment
  - python setup.py install
  # install remaining from pip
  - pip install -r requirements
  - pip install flake8
  - pip install codecov

# command to run before the tests
before_script:
  - "flake8 symbtrextras --ignore=E501"

# command to run tests
script:
  - nosetests symbtrextras/unittests --with-coverage

# final commands
after_success:
  - codecov
